---
title: "01-comparing-2-groups"
date: "`r format(Sys.time(), '%d %B %Y')`"
---

```{r setup, include=FALSE}
source( "../R_course_setup.R" );
```

### Quick Task

Perform the Student's t test and the Wilcoxon rank-sum test to compare the performance for each events and the total number of points between both events in the `decathlon2` dataset. Do you see any differences between the test?

```{r}
library(factoextra)
data(decathlon2)
p.values <- NULL
t.statistic <- NULL
for (k in colnames(decathlon2)[c(1:10,12)]){
  print(k)
  formula <- as.formula(paste('decathlon2$', k, ' ~ decathlon2$Competition', sep = ''))
  t.test.deca <- t.test(formula)
  p.values <- c(p.values, t.test.deca$p.value)
  t.statistic <- c(t.statistic, t.test.deca$statistic)
  print(t.test.deca)
  wilcox.test.deca <- wilcox.test(formula, alternative = "two.sided", exact =F)
  print(wilcox.test.deca)
}

dataTests <- data.frame(name.variables = colnames(decathlon2)[c(1:10,12)], pvalue = p.values, statistic = t.statistic) 
```
