<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Data types, part 1 | Using R for data analysis</title>
  <meta name="description" content="This course teaches the basics of R, an open-source and free environment for statistical analyses. In this course we also teach the basics transparent and reproducible research. For this, we teach RMarkdown, a tool to make dynamic reports in R." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Data types, part 1 | Using R for data analysis" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This course teaches the basics of R, an open-source and free environment for statistical analyses. In this course we also teach the basics transparent and reproducible research. For this, we teach RMarkdown, a tool to make dynamic reports in R." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Data types, part 1 | Using R for data analysis" />
  
  <meta name="twitter:description" content="This course teaches the basics of R, an open-source and free environment for statistical analyses. In this course we also teach the basics transparent and reproducible research. For this, we teach RMarkdown, a tool to make dynamic reports in R." />
  



<meta name="date" content="2021-06-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="basics-of-r.html"/>
<link rel="next" href="data-types-part-2.html"/>
<script src="libs/header-attrs-2.8/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About this course</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#teachers"><i class="fa fa-check"></i>Teachers</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#goals-topics"><i class="fa fa-check"></i>Goals &amp; Topics</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#prerequisites"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#materials"><i class="fa fa-check"></i>Materials</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#programme"><i class="fa fa-check"></i>Programme</a>
<ul>
<li class="chapter" data-level="0.0.1" data-path="index.html"><a href="index.html#second-nki-edition-june-7th-8th-10th-and-11th-2021"><i class="fa fa-check"></i><b>0.0.1</b> Second NKI edition, June 7th, 8th, 10th, and 11th 2021</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="basics-of-r.html"><a href="basics-of-r.html"><i class="fa fa-check"></i><b>1</b> Basics of R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="basics-of-r.html"><a href="basics-of-r.html#data-sets"><i class="fa fa-check"></i><b>1.1</b> Data sets</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="basics-of-r.html"><a href="basics-of-r.html#pulse"><i class="fa fa-check"></i><b>1.1.1</b> Pulse</a></li>
<li class="chapter" data-level="1.1.2" data-path="basics-of-r.html"><a href="basics-of-r.html#survey"><i class="fa fa-check"></i><b>1.1.2</b> Survey</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="basics-of-r.html"><a href="basics-of-r.html#introduction"><i class="fa fa-check"></i><b>1.2</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="basics-of-r.html"><a href="basics-of-r.html#why-this-course"><i class="fa fa-check"></i><b>1.2.1</b> Why this course?</a></li>
<li class="chapter" data-level="1.2.2" data-path="basics-of-r.html"><a href="basics-of-r.html#what-is-r"><i class="fa fa-check"></i><b>1.2.2</b> What is R?</a></li>
<li class="chapter" data-level="1.2.3" data-path="basics-of-r.html"><a href="basics-of-r.html#r-and-rstudio"><i class="fa fa-check"></i><b>1.2.3</b> R and RStudio</a></li>
<li class="chapter" data-level="1.2.4" data-path="basics-of-r.html"><a href="basics-of-r.html#course-overview"><i class="fa fa-check"></i><b>1.2.4</b> Course overview</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="basics-of-r.html"><a href="basics-of-r.html#basics"><i class="fa fa-check"></i><b>1.3</b> Basics</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="basics-of-r.html"><a href="basics-of-r.html#r-as-a-calculator"><i class="fa fa-check"></i><b>1.3.1</b> R as a calculator</a></li>
<li class="chapter" data-level="1.3.2" data-path="basics-of-r.html"><a href="basics-of-r.html#variables"><i class="fa fa-check"></i><b>1.3.2</b> Variables</a></li>
<li class="chapter" data-level="1.3.3" data-path="basics-of-r.html"><a href="basics-of-r.html#vectors"><i class="fa fa-check"></i><b>1.3.3</b> Vectors</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="basics-of-r.html"><a href="basics-of-r.html#projects-and-scripts"><i class="fa fa-check"></i><b>1.4</b> Projects and scripts</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="basics-of-r.html"><a href="basics-of-r.html#projects"><i class="fa fa-check"></i><b>1.4.1</b> Projects</a></li>
<li class="chapter" data-level="1.4.2" data-path="basics-of-r.html"><a href="basics-of-r.html#reading-data"><i class="fa fa-check"></i><b>1.4.2</b> Reading data</a></li>
<li class="chapter" data-level="1.4.3" data-path="basics-of-r.html"><a href="basics-of-r.html#scripts"><i class="fa fa-check"></i><b>1.4.3</b> Scripts</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="basics-of-r.html"><a href="basics-of-r.html#data-frames-basics"><i class="fa fa-check"></i><b>1.5</b> Data frames (basics)</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="basics-of-r.html"><a href="basics-of-r.html#exploring"><i class="fa fa-check"></i><b>1.5.1</b> Exploring</a></li>
<li class="chapter" data-level="1.5.2" data-path="basics-of-r.html"><a href="basics-of-r.html#extracting"><i class="fa fa-check"></i><b>1.5.2</b> Extracting</a></li>
<li class="chapter" data-level="1.5.3" data-path="basics-of-r.html"><a href="basics-of-r.html#example-data"><i class="fa fa-check"></i><b>1.5.3</b> Example data</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="basics-of-r.html"><a href="basics-of-r.html#basic-data-types"><i class="fa fa-check"></i><b>1.6</b> Basic data types</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="basics-of-r.html"><a href="basics-of-r.html#types"><i class="fa fa-check"></i><b>1.6.1</b> Types</a></li>
<li class="chapter" data-level="1.6.2" data-path="basics-of-r.html"><a href="basics-of-r.html#vector-classes"><i class="fa fa-check"></i><b>1.6.2</b> Vector classes</a></li>
<li class="chapter" data-level="1.6.3" data-path="basics-of-r.html"><a href="basics-of-r.html#character-data"><i class="fa fa-check"></i><b>1.6.3</b> Character data</a></li>
<li class="chapter" data-level="1.6.4" data-path="basics-of-r.html"><a href="basics-of-r.html#factor---categorical-data"><i class="fa fa-check"></i><b>1.6.4</b> Factor - categorical data</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="basics-of-r.html"><a href="basics-of-r.html#functions-and-help-files"><i class="fa fa-check"></i><b>1.7</b> Functions and help files</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="basics-of-r.html"><a href="basics-of-r.html#function-arguments"><i class="fa fa-check"></i><b>1.7.1</b> Function arguments</a></li>
<li class="chapter" data-level="1.7.2" data-path="basics-of-r.html"><a href="basics-of-r.html#other-help-file-aspects"><i class="fa fa-check"></i><b>1.7.2</b> Other help file aspects</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-types-part-1.html"><a href="data-types-part-1.html"><i class="fa fa-check"></i><b>2</b> Data types, part 1</a>
<ul>
<li class="chapter" data-level="2.1" data-path="data-types-part-1.html"><a href="data-types-part-1.html#basic-data-types-cont."><i class="fa fa-check"></i><b>2.1</b> Basic data types (cont.)</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="data-types-part-1.html"><a href="data-types-part-1.html#missing-values"><i class="fa fa-check"></i><b>2.1.1</b> Missing values</a></li>
<li class="chapter" data-level="2.1.2" data-path="data-types-part-1.html"><a href="data-types-part-1.html#numeric-vectors"><i class="fa fa-check"></i><b>2.1.2</b> Numeric vectors</a></li>
<li class="chapter" data-level="2.1.3" data-path="data-types-part-1.html"><a href="data-types-part-1.html#character-vectors"><i class="fa fa-check"></i><b>2.1.3</b> Character vectors</a></li>
<li class="chapter" data-level="2.1.4" data-path="data-types-part-1.html"><a href="data-types-part-1.html#logical-vectors"><i class="fa fa-check"></i><b>2.1.4</b> Logical vectors</a></li>
<li class="chapter" data-level="2.1.5" data-path="data-types-part-1.html"><a href="data-types-part-1.html#type-conversions"><i class="fa fa-check"></i><b>2.1.5</b> Type conversions</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="data-types-part-1.html"><a href="data-types-part-1.html#vectors-1"><i class="fa fa-check"></i><b>2.2</b> Vectors</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="data-types-part-1.html"><a href="data-types-part-1.html#square-brackets-operator"><i class="fa fa-check"></i><b>2.2.1</b> Square brackets operator</a></li>
<li class="chapter" data-level="2.2.2" data-path="data-types-part-1.html"><a href="data-types-part-1.html#other-useful-functions"><i class="fa fa-check"></i><b>2.2.2</b> Other useful functions</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="data-types-part-1.html"><a href="data-types-part-1.html#data-frames"><i class="fa fa-check"></i><b>2.3</b> Data frames</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="data-types-part-1.html"><a href="data-types-part-1.html#what-is-a-data-frame"><i class="fa fa-check"></i><b>2.3.1</b> What is a data frame</a></li>
<li class="chapter" data-level="2.3.2" data-path="data-types-part-1.html"><a href="data-types-part-1.html#creating"><i class="fa fa-check"></i><b>2.3.2</b> Creating</a></li>
<li class="chapter" data-level="2.3.3" data-path="data-types-part-1.html"><a href="data-types-part-1.html#properties"><i class="fa fa-check"></i><b>2.3.3</b> Properties</a></li>
<li class="chapter" data-level="2.3.4" data-path="data-types-part-1.html"><a href="data-types-part-1.html#content"><i class="fa fa-check"></i><b>2.3.4</b> Content</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="data-types-part-1.html"><a href="data-types-part-1.html#matrices"><i class="fa fa-check"></i><b>2.4</b> Matrices</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="data-types-part-1.html"><a href="data-types-part-1.html#what-is-a-matrix"><i class="fa fa-check"></i><b>2.4.1</b> What is a matrix</a></li>
<li class="chapter" data-level="2.4.2" data-path="data-types-part-1.html"><a href="data-types-part-1.html#creation"><i class="fa fa-check"></i><b>2.4.2</b> Creation</a></li>
<li class="chapter" data-level="2.4.3" data-path="data-types-part-1.html"><a href="data-types-part-1.html#dimensions-2"><i class="fa fa-check"></i><b>2.4.3</b> Dimensions</a></li>
<li class="chapter" data-level="2.4.4" data-path="data-types-part-1.html"><a href="data-types-part-1.html#settinggetting-names-of-the-columns-and-rows"><i class="fa fa-check"></i><b>2.4.4</b> Setting/getting names of the columns and rows</a></li>
<li class="chapter" data-level="2.4.5" data-path="data-types-part-1.html"><a href="data-types-part-1.html#getting-matrix-elements"><i class="fa fa-check"></i><b>2.4.5</b> Getting matrix elements</a></li>
<li class="chapter" data-level="2.4.6" data-path="data-types-part-1.html"><a href="data-types-part-1.html#useful-matrix-functions"><i class="fa fa-check"></i><b>2.4.6</b> Useful matrix functions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-types-part-2.html"><a href="data-types-part-2.html"><i class="fa fa-check"></i><b>3</b> Data types, part 2</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-types-part-2.html"><a href="data-types-part-2.html#r-scripts-and-reports-rmarkdown"><i class="fa fa-check"></i><b>3.1</b> R scripts and reports (Rmarkdown)</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-types-part-2.html"><a href="data-types-part-2.html#markdown-r-code-markdown-text-formating-language"><i class="fa fa-check"></i><b>3.1.1</b> Markdown : R code + Markdown text formating language</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-types-part-2.html"><a href="data-types-part-2.html#features-of-r-markdown"><i class="fa fa-check"></i><b>3.1.2</b> Features of R Markdown</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-types-part-2.html"><a href="data-types-part-2.html#lists"><i class="fa fa-check"></i><b>3.2</b> Lists</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="data-types-part-2.html"><a href="data-types-part-2.html#what-is-a-list"><i class="fa fa-check"></i><b>3.2.1</b> What is a list</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-types-part-2.html"><a href="data-types-part-2.html#creation-1"><i class="fa fa-check"></i><b>3.2.2</b> Creation</a></li>
<li class="chapter" data-level="3.2.3" data-path="data-types-part-2.html"><a href="data-types-part-2.html#length"><i class="fa fa-check"></i><b>3.2.3</b> Length</a></li>
<li class="chapter" data-level="3.2.4" data-path="data-types-part-2.html"><a href="data-types-part-2.html#getting-names-of-the-elements"><i class="fa fa-check"></i><b>3.2.4</b> Getting names of the elements</a></li>
<li class="chapter" data-level="3.2.5" data-path="data-types-part-2.html"><a href="data-types-part-2.html#getting-a-single-element"><i class="fa fa-check"></i><b>3.2.5</b> Getting a single element</a></li>
<li class="chapter" data-level="3.2.6" data-path="data-types-part-2.html"><a href="data-types-part-2.html#getting-multiple-elements-as-a-list"><i class="fa fa-check"></i><b>3.2.6</b> (*) Getting multiple elements as a list</a></li>
<li class="chapter" data-level="3.2.7" data-path="data-types-part-2.html"><a href="data-types-part-2.html#removing-an-element"><i class="fa fa-check"></i><b>3.2.7</b> (*) Removing an element</a></li>
<li class="chapter" data-level="3.2.8" data-path="data-types-part-2.html"><a href="data-types-part-2.html#adding-an-element"><i class="fa fa-check"></i><b>3.2.8</b> (*) Adding an element</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="data-types-part-2.html"><a href="data-types-part-2.html#basic-statistical-tests"><i class="fa fa-check"></i><b>3.3</b> Basic statistical tests</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="data-types-part-2.html"><a href="data-types-part-2.html#statistical-methods-with-r"><i class="fa fa-check"></i><b>3.3.1</b> Statistical methods with R</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="data-types-part-2.html"><a href="data-types-part-2.html#regression-and-formula-objects"><i class="fa fa-check"></i><b>3.4</b> Regression and formula objects</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="data-types-part-2.html"><a href="data-types-part-2.html#formula-objects"><i class="fa fa-check"></i><b>3.4.1</b> Formula objects</a></li>
<li class="chapter" data-level="3.4.2" data-path="data-types-part-2.html"><a href="data-types-part-2.html#simple-linear-regression"><i class="fa fa-check"></i><b>3.4.2</b> Simple linear regression</a></li>
<li class="chapter" data-level="3.4.3" data-path="data-types-part-2.html"><a href="data-types-part-2.html#multiple-regression-and-prediction"><i class="fa fa-check"></i><b>3.4.3</b> Multiple regression and prediction</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="data-types-part-2.html"><a href="data-types-part-2.html#factors-advanced"><i class="fa fa-check"></i><b>3.5</b> Factors (advanced)</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="data-types-part-2.html"><a href="data-types-part-2.html#factors-revisited"><i class="fa fa-check"></i><b>3.5.1</b> Factors revisited</a></li>
<li class="chapter" data-level="3.5.2" data-path="data-types-part-2.html"><a href="data-types-part-2.html#anova-and-regression-with-factors"><i class="fa fa-check"></i><b>3.5.2</b> ANOVA and regression with factors</a></li>
<li class="chapter" data-level="3.5.3" data-path="data-types-part-2.html"><a href="data-types-part-2.html#generalized-linear-models-and-survival"><i class="fa fa-check"></i><b>3.5.3</b> (*) Generalized linear models and survival</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>4</b> Functions</a>
<ul>
<li class="chapter" data-level="4.1" data-path="functions.html"><a href="functions.html#user-defined-functions"><i class="fa fa-check"></i><b>4.1</b> User-defined Functions</a></li>
<li class="chapter" data-level="4.2" data-path="functions.html"><a href="functions.html#control-flow-constructs"><i class="fa fa-check"></i><b>4.2</b> (*) Control flow constructs</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="functions.html"><a href="functions.html#sequential-execution"><i class="fa fa-check"></i><b>4.2.1</b> Sequential execution</a></li>
<li class="chapter" data-level="4.2.2" data-path="functions.html"><a href="functions.html#conditional-execution-if"><i class="fa fa-check"></i><b>4.2.2</b> Conditional execution: if</a></li>
<li class="chapter" data-level="4.2.3" data-path="functions.html"><a href="functions.html#conditional-execution-ifelse"><i class="fa fa-check"></i><b>4.2.3</b> Conditional execution: if/else</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="functions.html"><a href="functions.html#apply-family-apply-lapply-sapply-tapply"><i class="fa fa-check"></i><b>4.3</b> <code>apply</code> family: apply, lapply, sapply, tapply</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="functions.html"><a href="functions.html#applyx-margin-fun"><i class="fa fa-check"></i><b>4.3.1</b> apply(X, MARGIN, FUN, …)</a></li>
<li class="chapter" data-level="4.3.2" data-path="functions.html"><a href="functions.html#sapplyx-fun"><i class="fa fa-check"></i><b>4.3.2</b> sapply(X, FUN, …)</a></li>
<li class="chapter" data-level="4.3.3" data-path="functions.html"><a href="functions.html#lapplyx-fun-apply-a-function-to-a-listvector"><i class="fa fa-check"></i><b>4.3.3</b> lapply(X, FUN, …) : apply a function to a list/vector</a></li>
<li class="chapter" data-level="4.3.4" data-path="functions.html"><a href="functions.html#tapplyx-index-fun-apply-a-function-to-a-vector-according-to-groups-of-index"><i class="fa fa-check"></i><b>4.3.4</b> tapply(X, INDEX, FUN, …) : apply a function to a vector, according to groups of INDEX</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="functions.html"><a href="functions.html#type-checking"><i class="fa fa-check"></i><b>4.4</b> Type checking</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="functions.html"><a href="functions.html#is.-family-functions"><i class="fa fa-check"></i><b>4.4.1</b> is.* family functions</a></li>
<li class="chapter" data-level="4.4.2" data-path="functions.html"><a href="functions.html#stopwarning"><i class="fa fa-check"></i><b>4.4.2</b> (*) stop(…)/warning(…)</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="functions.html"><a href="functions.html#r-programming"><i class="fa fa-check"></i><b>4.5</b> (*) R programming</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="functions.html"><a href="functions.html#general-coding-conventions"><i class="fa fa-check"></i><b>4.5.1</b> General coding conventions</a></li>
<li class="chapter" data-level="4.5.2" data-path="functions.html"><a href="functions.html#finding-installing-and-loading-packages"><i class="fa fa-check"></i><b>4.5.2</b> Finding, installing and loading packages</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i>Appendix</a>
<ul>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#character-string-processing-pattern-matching"><i class="fa fa-check"></i>Character string processing &amp; Pattern matching</a>
<ul>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#learning-goals"><i class="fa fa-check"></i>Learning goals</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#quotes-and-escape-characters-characters-with-special-meaning"><i class="fa fa-check"></i>Quotes and escape characters (characters with special meaning)</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#character-string"><i class="fa fa-check"></i>Character string</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#paste-sep-collapse-null"><i class="fa fa-check"></i>paste(…, sep = " ", collapse = NULL):</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#pulse-data-set"><i class="fa fa-check"></i>Pulse data set</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#tolower-toupper-nchar"><i class="fa fa-check"></i>tolower, toupper, nchar</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#split-character-string-strsplitx-split"><i class="fa fa-check"></i>Split character string : strsplit(x, split, …):</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#rbind-cbind-combine-by-rows-or-columns"><i class="fa fa-check"></i>rbind(…), cbind(…) : combine by rows or columns</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#strsplitx-split"><i class="fa fa-check"></i>strsplit(x, split, …)</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#do.callwhat-args-execute-function-on-list-of-arguments"><i class="fa fa-check"></i>do.call(what, args, …) : execute function on list of arguments</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#greppattern-x-ignore.case-false-value-false"><i class="fa fa-check"></i>grep(pattern, x, ignore.case = FALSE, value = FALSE, … )</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#greplpattern-x-ignore.case-false"><i class="fa fa-check"></i>grepl(pattern, x, ignore.case = FALSE, …)</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#substrx-start-stop-extractreplace-substrings"><i class="fa fa-check"></i>substr(x, start, stop) : extract/replace substrings</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#gsubsubpattern-replacement-x-ignore.case-false"><i class="fa fa-check"></i>gsub/sub(pattern, replacement, x, ignore.case = FALSE, …)</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#extra-exercises"><i class="fa fa-check"></i>Extra exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#s3-and-s4-classes"><i class="fa fa-check"></i>S3 and S4 classes</a>
<ul>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#learning-goals-1"><i class="fa fa-check"></i>Learning goals</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#objects"><i class="fa fa-check"></i>Objects</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#s3"><i class="fa fa-check"></i>S3</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#s4"><i class="fa fa-check"></i>S4</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#making-errors-the-right-way"><i class="fa fa-check"></i>Making errors the right way</a>
<ul>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#annoying-errors"><i class="fa fa-check"></i>Annoying errors</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#how-to-correct-annoying-errors"><i class="fa fa-check"></i>How to correct (annoying) errors</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#dangerous-errors"><i class="fa fa-check"></i>Dangerous errors</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#how-to-avoid-dangerous-errors"><i class="fa fa-check"></i>How to avoid (dangerous) errors</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#useful-links"><i class="fa fa-check"></i>Useful links</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Using R for data analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-types-part-1" class="section level1" number="2">
<h1><span class="header-section-number">Chapter 2</span> Data types, part 1</h1>
<div id="basic-data-types-cont." class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> Basic data types (cont.)</h2>
<div id="missing-values" class="section level3" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> Missing values</h3>
<p>Numeric, character, logical vectors, factors might contain elements marked as ‘missing’.</p>
<p><code>NA</code> is a constant which indicates a missing value.</p>
<p><code>NA</code> values would appear in the course materials and tasks.</p>
</div>
<div id="numeric-vectors" class="section level3" number="2.1.2">
<h3><span class="header-section-number">2.1.2</span> Numeric vectors</h3>
<p>There are several ways to construct a vector of numbers.</p>
<div id="single-number-numeric-vector-with-a-single-element" class="section level4" number="2.1.2.1">
<h4><span class="header-section-number">2.1.2.1</span> Single number (numeric vector with a single element)</h4>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="data-types-part-1.html#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="dv">7</span></span></code></pre></div>
<pre><code>## [1] 7</code></pre>
</div>
<div id="multiple-numbers" class="section level4" number="2.1.2.2">
<h4><span class="header-section-number">2.1.2.2</span> Multiple numbers</h4>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="data-types-part-1.html#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>( <span class="dv">5</span>, <span class="sc">-</span><span class="fl">2.5</span>, <span class="cn">NA</span>, <span class="dv">7</span><span class="sc">+</span><span class="dv">3</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span> )</span></code></pre></div>
<pre><code>## [1]  5.0000000 -2.5000000         NA 10.0000000  0.3333333</code></pre>
</div>
<div id="sequence-of-numbers-one-by-one" class="section level4" number="2.1.2.3">
<h4><span class="header-section-number">2.1.2.3</span> Sequence of numbers (one by one)</h4>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="data-types-part-1.html#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="dv">3</span><span class="sc">:</span><span class="dv">17</span></span></code></pre></div>
<pre><code>##  [1]  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17</code></pre>
</div>
<div id="sequence-of-numbers" class="section level4" number="2.1.2.4">
<h4><span class="header-section-number">2.1.2.4</span> Sequence of numbers</h4>
<p>Sequence of numbers with a defined step:</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="data-types-part-1.html#cb143-1" aria-hidden="true" tabindex="-1"></a><span class="fu">seq</span>( <span class="dv">5</span>, <span class="dv">15</span>, <span class="dv">2</span> )</span></code></pre></div>
<pre><code>## [1]  5  7  9 11 13 15</code></pre>
</div>
<div id="combine-several-vectors-of-numbers" class="section level4" number="2.1.2.5">
<h4><span class="header-section-number">2.1.2.5</span> Combine (several) vectors of numbers</h4>
<p>Multiple vectors can be combined together:</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="data-types-part-1.html#cb145-1" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span></span>
<span id="cb145-2"><a href="data-types-part-1.html#cb145-2" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fu">seq</span>( <span class="dv">10</span>, <span class="dv">90</span>, <span class="dv">10</span> )</span>
<span id="cb145-3"><a href="data-types-part-1.html#cb145-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>( <span class="dv">0</span>, v, w, <span class="dv">100</span> )</span></code></pre></div>
<pre><code>##  [1]   0   1   2   3   4   5   6   7   8   9  10  20  30  40  50  60  70  80  90
## [20] 100</code></pre>
<hr />
<blockquote>
<p><em>Quick task(s)</em>:</p>
<p>Solve <a href="01_basic_data_types_cont.tasks.nocode.html#numeric">the task(s)</a>, and check your solution(s) <a href="01_basic_data_types_cont.tasks.code.html#numeric">here</a>.</p>
</blockquote>
<hr />
</div>
</div>
<div id="character-vectors" class="section level3" number="2.1.3">
<h3><span class="header-section-number">2.1.3</span> Character vectors</h3>
<p>There are several ways to construct a vector of texts.</p>
<div id="simple-single-text-character-vector-with-a-single-element" class="section level4" number="2.1.3.1">
<h4><span class="header-section-number">2.1.3.1</span> Simple single text (character vector with a single element)</h4>
<p>With double quotes:</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="data-types-part-1.html#cb147-1" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Bioinformatics&quot;</span></span></code></pre></div>
<pre><code>## [1] &quot;Bioinformatics&quot;</code></pre>
<p>Or, with single quotes:</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="data-types-part-1.html#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;Biostatistics&#39;</span></span></code></pre></div>
<pre><code>## [1] &quot;Biostatistics&quot;</code></pre>
</div>
<div id="multiple-texts" class="section level4" number="2.1.3.2">
<h4><span class="header-section-number">2.1.3.2</span> Multiple texts</h4>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="data-types-part-1.html#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>( <span class="st">&quot;Bioinformatics&quot;</span>, <span class="st">&quot;Biostatistics&quot;</span> )</span></code></pre></div>
<pre><code>## [1] &quot;Bioinformatics&quot; &quot;Biostatistics&quot;</code></pre>
</div>
<div id="lines-from-a-text-file" class="section level4" number="2.1.3.3">
<h4><span class="header-section-number">2.1.3.3</span> Lines from a text file</h4>
<p>Earlier we used <code>read.table</code> function to read a text file into a (two-dimensional) data frame. Here, use <code>readLines</code> function to read contents of the <code>pulse.txt</code> file into a (one-dimensional) character vector.</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="data-types-part-1.html#cb153-1" aria-hidden="true" tabindex="-1"></a>txt <span class="ot">&lt;-</span> <span class="fu">readLines</span>( <span class="st">&quot;data/pulse.txt&quot;</span> )</span></code></pre></div>
<p>Each element of the vector <code>txt</code> is a single line from the file. The file is stored in <code>tsv</code> (tab-separated values format), so the <code>\t</code> symbol separates the values of columns. These are the first 3 lines (the first one contains the header of the table):</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="data-types-part-1.html#cb154-1" aria-hidden="true" tabindex="-1"></a>txt <span class="ot">&lt;-</span> <span class="fu">readLines</span>( <span class="st">&quot;data/pulse.txt&quot;</span> )</span>
<span id="cb154-2"><a href="data-types-part-1.html#cb154-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>( txt, <span class="dv">3</span> )</span></code></pre></div>
<pre><code>## [1] &quot;name\theight\tweight\tage\tgender\tsmokes\talcohol\texercise\tran\tpulse1\tpulse2\tyear&quot;
## [2] &quot;1993_A\tBonnie\t173\t57\t18\tfemale\tno\tyes\tmoderate\tsat\t86\t88\t1993&quot;               
## [3] &quot;1993_B\tMelanie\t179\t58\t19\tfemale\tno\tyes\tmoderate\tran\t82\t150\t1993&quot;</code></pre>
<hr />
<blockquote>
<p><em>Quick task(s)</em>:</p>
<p>Solve <a href="01_basic_data_types_cont.tasks.nocode.html#character">the task(s)</a>, and check your solution(s) <a href="01_basic_data_types_cont.tasks.code.html#character">here</a>.</p>
</blockquote>
<hr />
</div>
</div>
<div id="logical-vectors" class="section level3" number="2.1.4">
<h3><span class="header-section-number">2.1.4</span> Logical vectors</h3>
<div id="elementary-logical-values" class="section level4" number="2.1.4.1">
<h4><span class="header-section-number">2.1.4.1</span> Elementary logical values</h4>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="data-types-part-1.html#cb156-1" aria-hidden="true" tabindex="-1"></a><span class="cn">TRUE</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="data-types-part-1.html#cb158-1" aria-hidden="true" tabindex="-1"></a><span class="cn">FALSE</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="data-types-part-1.html#cb160-1" aria-hidden="true" tabindex="-1"></a>T</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="data-types-part-1.html#cb162-1" aria-hidden="true" tabindex="-1"></a>F</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="data-types-part-1.html#cb164-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>( <span class="cn">FALSE</span>, F, <span class="cn">TRUE</span>, T )    <span class="co"># vector of logical values</span></span></code></pre></div>
<pre><code>## [1] FALSE FALSE  TRUE  TRUE</code></pre>
<p>(*) <code>NA</code> is a logical constant and it gets automatically converted to other types when necessary.</p>
</div>
<div id="logical-operators" class="section level4" number="2.1.4.2">
<h4><span class="header-section-number">2.1.4.2</span> Logical operators</h4>
<div id="negation" class="section level5" number="2.1.4.2.1">
<h5><span class="header-section-number">2.1.4.2.1</span> Negation</h5>
<p>Unary negation operator (denoted <code>!</code>):</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="data-types-part-1.html#cb166-1" aria-hidden="true" tabindex="-1"></a><span class="sc">!</span><span class="cn">TRUE</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="data-types-part-1.html#cb168-1" aria-hidden="true" tabindex="-1"></a><span class="sc">!</span><span class="cn">FALSE</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
</div>
<div id="and-operator" class="section level5" number="2.1.4.2.2">
<h5><span class="header-section-number">2.1.4.2.2</span> AND Operator <code>&amp;</code></h5>
<p>Binary operator AND (denoted <code>&amp;</code>) returns <code>TRUE</code> result when <code>all</code> its arguments are <code>TRUE</code>:</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="data-types-part-1.html#cb170-1" aria-hidden="true" tabindex="-1"></a><span class="cn">TRUE</span> <span class="sc">&amp;</span> <span class="cn">TRUE</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>Otherwise returns <code>FALSE</code>:</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="data-types-part-1.html#cb172-1" aria-hidden="true" tabindex="-1"></a><span class="cn">FALSE</span> <span class="sc">&amp;</span> <span class="cn">TRUE</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="data-types-part-1.html#cb174-1" aria-hidden="true" tabindex="-1"></a><span class="cn">FALSE</span> <span class="sc">&amp;</span> <span class="cn">FALSE</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
</div>
<div id="or-operator" class="section level5" number="2.1.4.2.3">
<h5><span class="header-section-number">2.1.4.2.3</span> OR operator <code>|</code></h5>
<p>Binary operator OR (denoted <code>|</code>) returns <code>TRUE</code> result when <code>any</code> (at least one) of its arguments is <code>TRUE</code>:</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="data-types-part-1.html#cb176-1" aria-hidden="true" tabindex="-1"></a><span class="cn">TRUE</span> <span class="sc">|</span> <span class="cn">TRUE</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="data-types-part-1.html#cb178-1" aria-hidden="true" tabindex="-1"></a><span class="cn">FALSE</span> <span class="sc">|</span> <span class="cn">TRUE</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>Otherwise returns <code>FALSE</code>:</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="data-types-part-1.html#cb180-1" aria-hidden="true" tabindex="-1"></a><span class="cn">FALSE</span> <span class="sc">|</span> <span class="cn">FALSE</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
</div>
</div>
<div id="relational-operators" class="section level4" number="2.1.4.3">
<h4><span class="header-section-number">2.1.4.3</span> Relational operators</h4>
<div id="equality-operator" class="section level5" number="2.1.4.3.1">
<h5><span class="header-section-number">2.1.4.3.1</span> Equality operator <code>==</code></h5>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="data-types-part-1.html#cb182-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">==</span> <span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="data-types-part-1.html#cb184-1" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;Bioinformatics&quot;</span> <span class="sc">==</span> <span class="st">&quot;Biostatistics&quot;</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="data-types-part-1.html#cb186-1" aria-hidden="true" tabindex="-1"></a><span class="cn">FALSE</span> <span class="sc">==</span> F</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
</div>
<div id="inequality-operators" class="section level5" number="2.1.4.3.2">
<h5><span class="header-section-number">2.1.4.3.2</span> Inequality operators</h5>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="data-types-part-1.html#cb188-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">!=</span> <span class="dv">2</span>    <span class="co"># unequal  </span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="data-types-part-1.html#cb190-1" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;a&quot;</span> <span class="sc">!=</span> <span class="st">&quot;A&quot;</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="data-types-part-1.html#cb192-1" aria-hidden="true" tabindex="-1"></a><span class="cn">FALSE</span> <span class="sc">!=</span> T</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="data-types-part-1.html#cb194-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">&lt;</span> <span class="dv">2</span>     <span class="co"># less than</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="data-types-part-1.html#cb196-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">&gt;</span> <span class="dv">2</span>     <span class="co"># greater than</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="data-types-part-1.html#cb198-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">&lt;=</span> <span class="dv">2</span>    <span class="co"># less or equal </span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="data-types-part-1.html#cb200-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">&gt;=</span> <span class="dv">2</span>    <span class="co"># greater or equal</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
</div>
</div>
<div id="comparison-of-two-vectors" class="section level4" number="2.1.4.4">
<h4><span class="header-section-number">2.1.4.4</span> Comparison of two vectors</h4>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="data-types-part-1.html#cb202-1" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span> )</span>
<span id="cb202-2"><a href="data-types-part-1.html#cb202-2" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">0</span> )</span>
<span id="cb202-3"><a href="data-types-part-1.html#cb202-3" aria-hidden="true" tabindex="-1"></a>v <span class="sc">==</span> w</span></code></pre></div>
<pre><code>## [1] FALSE FALSE  TRUE FALSE FALSE</code></pre>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="data-types-part-1.html#cb204-1" aria-hidden="true" tabindex="-1"></a>v <span class="sc">!=</span> w</span></code></pre></div>
<pre><code>## [1]  TRUE  TRUE FALSE  TRUE  TRUE</code></pre>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="data-types-part-1.html#cb206-1" aria-hidden="true" tabindex="-1"></a>v <span class="sc">&lt;</span> w</span></code></pre></div>
<pre><code>## [1]  TRUE  TRUE FALSE FALSE FALSE</code></pre>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="data-types-part-1.html#cb208-1" aria-hidden="true" tabindex="-1"></a>v <span class="sc">&lt;=</span> w</span></code></pre></div>
<pre><code>## [1]  TRUE  TRUE  TRUE FALSE FALSE</code></pre>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="data-types-part-1.html#cb210-1" aria-hidden="true" tabindex="-1"></a>v <span class="sc">&gt;=</span> w</span></code></pre></div>
<pre><code>## [1] FALSE FALSE  TRUE  TRUE  TRUE</code></pre>
<hr />
<blockquote>
<p><em>Quick task(s)</em>:</p>
<p>Solve <a href="01_basic_data_types_cont.tasks.nocode.html#logical">the task(s)</a>, and check your solution(s) <a href="01_basic_data_types_cont.tasks.code.html#logical">here</a>.</p>
</blockquote>
<hr />
</div>
</div>
<div id="type-conversions" class="section level3" number="2.1.5">
<h3><span class="header-section-number">2.1.5</span> Type conversions</h3>
<p>Sometimes a conversion to a vector of certain type might be needed.
The family of functions: <code>as.numeric</code>, <code>as.character</code>, <code>as.logical</code> take as an argument a vector of any type and return a vector of the type given in the function name.
When the conversion of an element is not possible, <code>NA</code> value is used.</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="data-types-part-1.html#cb212-1" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="dv">101</span><span class="sc">:</span><span class="dv">110</span></span>
<span id="cb212-2"><a href="data-types-part-1.html#cb212-2" aria-hidden="true" tabindex="-1"></a>v</span></code></pre></div>
<pre><code>##  [1] 101 102 103 104 105 106 107 108 109 110</code></pre>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="data-types-part-1.html#cb214-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.character</span>( v )</span></code></pre></div>
<pre><code>##  [1] &quot;101&quot; &quot;102&quot; &quot;103&quot; &quot;104&quot; &quot;105&quot; &quot;106&quot; &quot;107&quot; &quot;108&quot; &quot;109&quot; &quot;110&quot;</code></pre>
<hr />
<blockquote>
<p><em>Quick task(s)</em>:</p>
<p>Solve <a href="01_basic_data_types_cont.tasks.nocode.html#conversions">the task(s)</a>, and check your solution(s) <a href="01_basic_data_types_cont.tasks.code.html#conversions">here</a>.</p>
</blockquote>
<hr />
</div>
</div>
<div id="vectors-1" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Vectors</h2>
<p>Vectors are data structures which are able to store multiple elements in a defined order.</p>
<p>There are several ways to access (single/multiple) elements from vectors which are discussed below.</p>
<div id="square-brackets-operator" class="section level3" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Square brackets operator</h3>
<div id="by-numbers" class="section level4" number="2.2.1.1">
<h4><span class="header-section-number">2.2.1.1</span> By numbers</h4>
<p>Vector elements are kept at successive, numbered (indexed) positions.
R vectors keep the first element at index 1 and the last element at index which can be obtained with the function <code>length</code>.</p>
<p>The indices can be used to fetch elements from the corresponding positions with the square bracket operators <code>[ pos ]</code>.</p>
<p>Let’s take a vector:</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="data-types-part-1.html#cb216-1" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="dv">101</span><span class="sc">:</span><span class="dv">110</span></span></code></pre></div>
<p>To get the first element of <code>v</code>:</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="data-types-part-1.html#cb217-1" aria-hidden="true" tabindex="-1"></a>v[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 101</code></pre>
<p>To get the last element of <code>v</code>:</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="data-types-part-1.html#cb219-1" aria-hidden="true" tabindex="-1"></a>v[ <span class="fu">length</span>( v ) ]</span></code></pre></div>
<pre><code>## [1] 110</code></pre>
<p>To get an element at a given index:</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="data-types-part-1.html#cb221-1" aria-hidden="true" tabindex="-1"></a>v[ <span class="dv">5</span> ]</span></code></pre></div>
<pre><code>## [1] 105</code></pre>
<p>Setting a single element:</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="data-types-part-1.html#cb223-1" aria-hidden="true" tabindex="-1"></a>v</span></code></pre></div>
<pre><code>##  [1] 101 102 103 104 105 106 107 108 109 110</code></pre>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="data-types-part-1.html#cb225-1" aria-hidden="true" tabindex="-1"></a>v[ <span class="dv">2</span> ] <span class="ot">&lt;-</span> <span class="dv">22</span></span>
<span id="cb225-2"><a href="data-types-part-1.html#cb225-2" aria-hidden="true" tabindex="-1"></a>v</span></code></pre></div>
<pre><code>##  [1] 101  22 103 104 105 106 107 108 109 110</code></pre>
<p>Getting multiple elements:</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="data-types-part-1.html#cb227-1" aria-hidden="true" tabindex="-1"></a>v[ <span class="fu">c</span>( <span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">7</span> ) ]</span></code></pre></div>
<pre><code>## [1]  22 104 107</code></pre>
<p>Setting multiple elements:</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="data-types-part-1.html#cb229-1" aria-hidden="true" tabindex="-1"></a>v[ <span class="fu">c</span>( <span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">7</span> ) ] <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="dv">22</span>, <span class="dv">24</span>, <span class="dv">27</span> )</span>
<span id="cb229-2"><a href="data-types-part-1.html#cb229-2" aria-hidden="true" tabindex="-1"></a>v</span></code></pre></div>
<pre><code>##  [1] 101  22 103  24 105 106  27 108 109 110</code></pre>
</div>
<div id="by-names" class="section level4" number="2.2.1.2">
<h4><span class="header-section-number">2.2.1.2</span> By names</h4>
<p>Elements of the vectors can also be given names, i.e. <code>named vector</code>. Let’s take a vector:</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="data-types-part-1.html#cb231-1" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="dv">101</span><span class="sc">:</span><span class="dv">110</span></span>
<span id="cb231-2"><a href="data-types-part-1.html#cb231-2" aria-hidden="true" tabindex="-1"></a>v</span></code></pre></div>
<pre><code>##  [1] 101 102 103 104 105 106 107 108 109 110</code></pre>
<p>Setting names of vector elements:</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="data-types-part-1.html#cb233-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>( v ) <span class="ot">&lt;-</span> LETTERS[ <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>( v ) ]</span>
<span id="cb233-2"><a href="data-types-part-1.html#cb233-2" aria-hidden="true" tabindex="-1"></a>v</span></code></pre></div>
<pre><code>##   A   B   C   D   E   F   G   H   I   J 
## 101 102 103 104 105 106 107 108 109 110</code></pre>
<p>Getting names of vector elements:</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="data-types-part-1.html#cb235-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>( v )</span></code></pre></div>
<pre><code>##  [1] &quot;A&quot; &quot;B&quot; &quot;C&quot; &quot;D&quot; &quot;E&quot; &quot;F&quot; &quot;G&quot; &quot;H&quot; &quot;I&quot; &quot;J&quot;</code></pre>
<p>Accessing elements (single or multiple) by names:</p>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="data-types-part-1.html#cb237-1" aria-hidden="true" tabindex="-1"></a>v[ <span class="st">&quot;C&quot;</span> ]</span></code></pre></div>
<pre><code>##   C 
## 103</code></pre>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="data-types-part-1.html#cb239-1" aria-hidden="true" tabindex="-1"></a>v[ <span class="fu">c</span>( <span class="st">&quot;F&quot;</span>, <span class="st">&quot;H&quot;</span> ) ]</span></code></pre></div>
<pre><code>##   F   H 
## 106 108</code></pre>
</div>
<div id="by-condition-logical-indices" class="section level4" number="2.2.1.3">
<h4><span class="header-section-number">2.2.1.3</span> By condition (logical indices)</h4>
<p>Let’s take a vector:</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="data-types-part-1.html#cb241-1" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="dv">101</span><span class="sc">:</span><span class="dv">110</span></span>
<span id="cb241-2"><a href="data-types-part-1.html#cb241-2" aria-hidden="true" tabindex="-1"></a>v</span></code></pre></div>
<pre><code>##  [1] 101 102 103 104 105 106 107 108 109 110</code></pre>
<p>Now let’s construct a logical vector <code>idx</code> with the same number of elements as <code>v</code>:</p>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="data-types-part-1.html#cb243-1" aria-hidden="true" tabindex="-1"></a>idx <span class="ot">&lt;-</span> <span class="fu">c</span>( F, F, F, T, F, T, F, F, T, <span class="cn">NA</span> )</span></code></pre></div>
<p><code>v</code> can now be “filtered through” <code>idx</code>. The elements of <code>v</code> corresponding to positions in <code>idx</code> are selected or not according to:</p>
<ul>
<li><code>TRUE</code> in <code>idx</code>, then the element appears in the result;</li>
<li><code>NA</code> in <code>idx</code>, then the element is substituted with <code>NA</code> in the result;</li>
<li><code>FALSE</code> in <code>idx</code>, then the element is skipped.</li>
</ul>
<p>In the example above:</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="data-types-part-1.html#cb244-1" aria-hidden="true" tabindex="-1"></a>v[ idx ]</span></code></pre></div>
<pre><code>## [1] 104 106 109  NA</code></pre>
<p>A logical vector like <code>idx</code> is typically a result of equality/comparison, or is generated by specialized functions. For example, if we wish to select entries in <code>v</code> that have values at least equal to 102 and smaller than 106, we could use:</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="data-types-part-1.html#cb246-1" aria-hidden="true" tabindex="-1"></a>v</span></code></pre></div>
<pre><code>##  [1] 101 102 103 104 105 106 107 108 109 110</code></pre>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="data-types-part-1.html#cb248-1" aria-hidden="true" tabindex="-1"></a>idx <span class="ot">&lt;-</span> v <span class="sc">&gt;=</span> <span class="dv">102</span> <span class="sc">&amp;</span> v <span class="sc">&lt;</span> <span class="dv">106</span></span>
<span id="cb248-2"><a href="data-types-part-1.html#cb248-2" aria-hidden="true" tabindex="-1"></a>idx</span></code></pre></div>
<pre><code>##  [1] FALSE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE</code></pre>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="data-types-part-1.html#cb250-1" aria-hidden="true" tabindex="-1"></a>v[ idx ]</span></code></pre></div>
<pre><code>## [1] 102 103 104 105</code></pre>
<p>Indices given by a logical vector are referred to as <em>logical indices</em>.</p>
<hr />
<blockquote>
<p><em>Quick task(s)</em>:</p>
<p>Solve <a href="02_selecting.tasks.nocode.html#brackets">the task(s)</a>, and check your solution(s) <a href="02_selecting.tasks.code.html#brackets">here</a>.</p>
</blockquote>
<hr />
</div>
</div>
<div id="other-useful-functions" class="section level3" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> Other useful functions</h3>
<p>Other functions which are in general useful are:</p>
<ul>
<li><code>sort()</code>: sorts the elements of a vector:</li>
</ul>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="data-types-part-1.html#cb252-1" aria-hidden="true" tabindex="-1"></a>v</span></code></pre></div>
<pre><code>##  [1] 101 102 103 104 105 106 107 108 109 110</code></pre>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="data-types-part-1.html#cb254-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(v)</span></code></pre></div>
<pre><code>##  [1] 101 102 103 104 105 106 107 108 109 110</code></pre>
<ul>
<li><code>unique()</code>: returns a vector containing the unique entries of a vector:</li>
</ul>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb256-1"><a href="data-types-part-1.html#cb256-1" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">1</span>)</span>
<span id="cb256-2"><a href="data-types-part-1.html#cb256-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(u)</span></code></pre></div>
<pre><code>## [1] 5 4 3 1</code></pre>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb258-1"><a href="data-types-part-1.html#cb258-1" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Monday&quot;</span>, <span class="st">&quot;Tuesday&quot;</span>, <span class="st">&quot;Thursday&quot;</span>, <span class="st">&quot;Friday&quot;</span>, <span class="st">&quot;Monday&quot;</span>, <span class="st">&quot;Wednesday&quot;</span>, <span class="st">&quot;Thursday&quot;</span>)</span>
<span id="cb258-2"><a href="data-types-part-1.html#cb258-2" aria-hidden="true" tabindex="-1"></a>w</span></code></pre></div>
<pre><code>## [1] &quot;Monday&quot;    &quot;Tuesday&quot;   &quot;Thursday&quot;  &quot;Friday&quot;    &quot;Monday&quot;    &quot;Wednesday&quot;
## [7] &quot;Thursday&quot;</code></pre>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="data-types-part-1.html#cb260-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(w)</span></code></pre></div>
<pre><code>## [1] &quot;Monday&quot;    &quot;Tuesday&quot;   &quot;Thursday&quot;  &quot;Friday&quot;    &quot;Wednesday&quot;</code></pre>
<ul>
<li><code>duplicated()</code>: returns a logical vector indicating which entries are duplicated or not:</li>
</ul>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="data-types-part-1.html#cb262-1" aria-hidden="true" tabindex="-1"></a><span class="fu">duplicated</span>(u)</span></code></pre></div>
<pre><code>## [1] FALSE  TRUE FALSE  TRUE FALSE FALSE</code></pre>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="data-types-part-1.html#cb264-1" aria-hidden="true" tabindex="-1"></a><span class="fu">duplicated</span>(w)</span></code></pre></div>
<pre><code>## [1] FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE</code></pre>
<p>So, in order to select all duplicated entries, the following could be used:</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="data-types-part-1.html#cb266-1" aria-hidden="true" tabindex="-1"></a>u[ <span class="fu">duplicated</span>(u) ]</span></code></pre></div>
<pre><code>## [1] 5 4</code></pre>
<hr />
<blockquote>
<p><em>Quick task(s)</em>:</p>
<p>Solve <a href="02_selecting.tasks.nocode.html#utility">the task(s)</a>, and check your solution(s) <a href="02_selecting.tasks.code.html#utility">here</a>.</p>
</blockquote>
<hr />
</div>
</div>
<div id="data-frames" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> Data frames</h2>
<div id="what-is-a-data-frame" class="section level3" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> What is a data frame</h3>
<center>
<img src="figure/Data_types_mdfl.png" title="fig:" alt="Vectors" />
</center>
<p>Data frame is a collection of variables represented as vectors of the same length.</p>
<p>Therefore, all the vectors (columns) should have unique names.</p>
<p>Rows represent separate records.</p>
<p>Rows might have names as well (although for new code, better create a separate column with names).</p>
</div>
<div id="creating" class="section level3" number="2.3.2">
<h3><span class="header-section-number">2.3.2</span> Creating</h3>
<div id="from-manually-provided-vectors" class="section level4" number="2.3.2.1">
<h4><span class="header-section-number">2.3.2.1</span> From manually provided vectors</h4>
<p>An example data frame built of <code>character</code>, <code>numeric</code> and <code>logical</code> vectors:</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb268-1"><a href="data-types-part-1.html#cb268-1" aria-hidden="true" tabindex="-1"></a>ids <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;D&quot;</span>, <span class="st">&quot;E&quot;</span> );</span>
<span id="cb268-2"><a href="data-types-part-1.html#cb268-2" aria-hidden="true" tabindex="-1"></a>ns <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="st">&quot;Amy&quot;</span>, <span class="st">&quot;Bob&quot;</span>, <span class="st">&quot;Dan&quot;</span>, <span class="st">&quot;Eve&quot;</span> )</span>
<span id="cb268-3"><a href="data-types-part-1.html#cb268-3" aria-hidden="true" tabindex="-1"></a>as <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="dv">40</span>, <span class="cn">NA</span>, <span class="dv">6</span>, <span class="dv">16</span> )</span>
<span id="cb268-4"><a href="data-types-part-1.html#cb268-4" aria-hidden="true" tabindex="-1"></a>ss <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="cn">TRUE</span>, <span class="cn">NA</span>, <span class="cn">FALSE</span>, <span class="cn">FALSE</span> )</span>
<span id="cb268-5"><a href="data-types-part-1.html#cb268-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb268-6"><a href="data-types-part-1.html#cb268-6" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb268-7"><a href="data-types-part-1.html#cb268-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">row.names =</span> ids,</span>
<span id="cb268-8"><a href="data-types-part-1.html#cb268-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">name =</span> ns,</span>
<span id="cb268-9"><a href="data-types-part-1.html#cb268-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> as,</span>
<span id="cb268-10"><a href="data-types-part-1.html#cb268-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">smoker =</span> ss</span>
<span id="cb268-11"><a href="data-types-part-1.html#cb268-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb268-12"><a href="data-types-part-1.html#cb268-12" aria-hidden="true" tabindex="-1"></a>d</span></code></pre></div>
<pre><code>##   name age smoker
## A  Amy  40   TRUE
## B  Bob  NA     NA
## D  Dan   6  FALSE
## E  Eve  16  FALSE</code></pre>
<p>The class of <code>d</code> is:</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="data-types-part-1.html#cb270-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( d )</span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<p>Function <code>str</code> gives a compact display of an object structure/content:</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="data-types-part-1.html#cb272-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>( d )</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    4 obs. of  3 variables:
##  $ name  : chr  &quot;Amy&quot; &quot;Bob&quot; &quot;Dan&quot; &quot;Eve&quot;
##  $ age   : num  40 NA 6 16
##  $ smoker: logi  TRUE NA FALSE FALSE</code></pre>
</div>
<div id="import-from-files" class="section level4" number="2.3.2.2">
<h4><span class="header-section-number">2.3.2.2</span> Import from files</h4>
<p>Datasets my come in various formats, e.g. <code>.tsv</code>, <code>.csv</code>, <code>.xls(x)</code>, <code>.sav</code>, <code>.txt</code> etc. R provides functions to import these formats as data.frame.</p>
<p><em>Note</em>: always after a file is read the columns must be checked whether their class and values are as expected. Additional conversions might be necessary (e.g. declaring factor levels, order of factor levels).</p>
<div id="tsv-file" class="section level5" number="2.3.2.2.1">
<h5><span class="header-section-number">2.3.2.2.1</span> TSV file</h5>
<p>For files stored in <a href="https://en.wikipedia.org/wiki/Tab-separated_values">tab-separated files (<code>tsv</code>) format</a> use:</p>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb274-1"><a href="data-types-part-1.html#cb274-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read.table</span>( <span class="st">&quot;data/pulse.tsv&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>, <span class="at">sep =</span> <span class="st">&quot;</span><span class="sc">\t</span><span class="st">&quot;</span> )</span></code></pre></div>
<pre><code># To get &#39;pulse.tsv&#39; directly from the server, use:
# d &lt;- read.table( url( &quot;https://barmsijs.lumc.nl/R_course/index.html/tree/master/data/pulse.tsv&quot; ), header = TRUE, sep = &quot;\t&quot; )</code></pre>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="data-types-part-1.html#cb276-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>( d )</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    110 obs. of  12 variables:
##  $ name    : chr  &quot;Bonnie&quot; &quot;Melanie&quot; &quot;Consuelo&quot; &quot;Travis&quot; ...
##  $ height  : int  173 179 167 195 173 184 162 169 164 168 ...
##  $ weight  : num  57 58 62 84 64 74 57 55 56 60 ...
##  $ age     : int  18 19 18 18 18 22 20 18 19 23 ...
##  $ gender  : chr  &quot;female&quot; &quot;female&quot; &quot;female&quot; &quot;male&quot; ...
##  $ smokes  : chr  &quot;no&quot; &quot;no&quot; &quot;no&quot; &quot;no&quot; ...
##  $ alcohol : chr  &quot;yes&quot; &quot;yes&quot; &quot;yes&quot; &quot;yes&quot; ...
##  $ exercise: chr  &quot;moderate&quot; &quot;moderate&quot; &quot;high&quot; &quot;high&quot; ...
##  $ ran     : chr  &quot;sat&quot; &quot;ran&quot; &quot;ran&quot; &quot;sat&quot; ...
##  $ pulse1  : int  86 82 96 71 90 78 68 71 68 88 ...
##  $ pulse2  : int  88 150 176 73 88 141 72 77 68 150 ...
##  $ year    : int  1993 1993 1993 1993 1993 1993 1993 1993 1993 1993 ...</code></pre>
</div>
<div id="csv-file" class="section level5" number="2.3.2.2.2">
<h5><span class="header-section-number">2.3.2.2.2</span> CSV file</h5>
<p>Data frames (tables) stored in files in <a href="https://en.wikipedia.org/wiki/Comma-separated_values">comma-separated values (<code>csv</code>) format</a> can be read with:</p>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb278-1"><a href="data-types-part-1.html#cb278-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read.csv</span>( <span class="st">&quot;data/pulse.csv&quot;</span> );</span></code></pre></div>
<pre><code># To get &#39;pulse.csv&#39; directly from the server, use:
# d &lt;- read.csv( url( &quot;https://barmsijs.lumc.nl/R_course/index.html/tree/master/data/pulse.csv&quot; ) )</code></pre>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="data-types-part-1.html#cb280-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>( d )</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    110 obs. of  13 variables:
##  $ id      : chr  &quot;1993_A&quot; &quot;1993_B&quot; &quot;1993_C&quot; &quot;1993_D&quot; ...
##  $ name    : chr  &quot;Bonnie&quot; &quot;Melanie&quot; &quot;Consuelo&quot; &quot;Travis&quot; ...
##  $ height  : int  173 179 167 195 173 184 162 169 164 168 ...
##  $ weight  : num  57 58 62 84 64 74 57 55 56 60 ...
##  $ age     : int  18 19 18 18 18 22 20 18 19 23 ...
##  $ gender  : chr  &quot;female&quot; &quot;female&quot; &quot;female&quot; &quot;male&quot; ...
##  $ smokes  : chr  &quot;no&quot; &quot;no&quot; &quot;no&quot; &quot;no&quot; ...
##  $ alcohol : chr  &quot;yes&quot; &quot;yes&quot; &quot;yes&quot; &quot;yes&quot; ...
##  $ exercise: chr  &quot;moderate&quot; &quot;moderate&quot; &quot;high&quot; &quot;high&quot; ...
##  $ ran     : chr  &quot;sat&quot; &quot;ran&quot; &quot;ran&quot; &quot;sat&quot; ...
##  $ pulse1  : int  86 82 96 71 90 78 68 71 68 88 ...
##  $ pulse2  : int  88 150 176 73 88 141 72 77 68 150 ...
##  $ year    : int  1993 1993 1993 1993 1993 1993 1993 1993 1993 1993 ...</code></pre>
</div>
<div id="microsoft-excel-file" class="section level5" number="2.3.2.2.3">
<h5><span class="header-section-number">2.3.2.2.3</span> Microsoft Excel file</h5>
<p>Reading Microsoft Excel files requires an additional library/package, which needs to be installed first. There exists several packages providing reading of Excel files.</p>
<div id="with-package-readxl" class="section level6" number="2.3.2.2.3.1">
<h6><span class="header-section-number">2.3.2.2.3.1</span> With package readxl</h6>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="data-types-part-1.html#cb282-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages( &quot;readxl&quot; )</span></span>
<span id="cb282-2"><a href="data-types-part-1.html#cb282-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>( readxl );</span>
<span id="cb282-3"><a href="data-types-part-1.html#cb282-3" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read_excel</span>( <span class="st">&quot;data/pulse.xlsx&quot;</span>, <span class="at">sheet =</span> <span class="dv">1</span> );</span>
<span id="cb282-4"><a href="data-types-part-1.html#cb282-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>( d );</span></code></pre></div>
<pre><code>## tibble [110 x 13] (S3: tbl_df/tbl/data.frame)
##  $ id      : chr [1:110] &quot;1993_A&quot; &quot;1993_B&quot; &quot;1993_C&quot; &quot;1993_D&quot; ...
##  $ name    : chr [1:110] &quot;Bonnie&quot; &quot;Melanie&quot; &quot;Consuelo&quot; &quot;Travis&quot; ...
##  $ height  : num [1:110] 173 179 167 195 173 184 162 169 164 168 ...
##  $ weight  : num [1:110] 57 58 62 84 64 74 57 55 56 60 ...
##  $ age     : num [1:110] 18 19 18 18 18 22 20 18 19 23 ...
##  $ gender  : chr [1:110] &quot;female&quot; &quot;female&quot; &quot;female&quot; &quot;male&quot; ...
##  $ smokes  : chr [1:110] &quot;no&quot; &quot;no&quot; &quot;no&quot; &quot;no&quot; ...
##  $ alcohol : chr [1:110] &quot;yes&quot; &quot;yes&quot; &quot;yes&quot; &quot;yes&quot; ...
##  $ exercise: chr [1:110] &quot;moderate&quot; &quot;moderate&quot; &quot;high&quot; &quot;high&quot; ...
##  $ ran     : chr [1:110] &quot;sat&quot; &quot;ran&quot; &quot;ran&quot; &quot;sat&quot; ...
##  $ pulse1  : chr [1:110] &quot;86&quot; &quot;82&quot; &quot;96&quot; &quot;71&quot; ...
##  $ pulse2  : chr [1:110] &quot;88&quot; &quot;150&quot; &quot;176&quot; &quot;73&quot; ...
##  $ year    : num [1:110] 1993 1993 1993 1993 1993 ...</code></pre>
</div>
<div id="with-package-gdata" class="section level6" number="2.3.2.2.3.2">
<h6><span class="header-section-number">2.3.2.2.3.2</span> With package gdata</h6>
<p>Please note that <code>gdata</code> package requires additional PERL packages to be installed; <code>readxl</code> seems to be easier to use.</p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb284-1"><a href="data-types-part-1.html#cb284-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages( &quot;gdata&quot; )</span></span>
<span id="cb284-2"><a href="data-types-part-1.html#cb284-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>( gdata )</span>
<span id="cb284-3"><a href="data-types-part-1.html#cb284-3" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read.xls</span>( <span class="st">&quot;data/pulse.xlsx&quot;</span>, <span class="at">sheet =</span> <span class="dv">1</span> )</span>
<span id="cb284-4"><a href="data-types-part-1.html#cb284-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>( d )</span></code></pre></div>
</div>
</div>
</div>
<div id="spss-files" class="section level4" number="2.3.2.3">
<h4><span class="header-section-number">2.3.2.3</span> SPSS files</h4>
<p>Reading SPSS files requires an additional library/package <code>foreign</code> (normally installed with R distribution).</p>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="data-types-part-1.html#cb285-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>( foreign )</span>
<span id="cb285-2"><a href="data-types-part-1.html#cb285-2" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read.spss</span>( <span class="st">&quot;data/pulse.sav&quot;</span>, <span class="at">to.data.frame =</span> <span class="cn">TRUE</span> )</span>
<span id="cb285-3"><a href="data-types-part-1.html#cb285-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>( d )</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    110 obs. of  13 variables:
##  $ id      : chr  &quot;1993_A&quot; &quot;1993_B&quot; &quot;1993_C&quot; &quot;1993_D&quot; ...
##  $ name    : chr  &quot;Bonnie     &quot; &quot;Melanie    &quot; &quot;Consuelo   &quot; &quot;Travis     &quot; ...
##  $ height  : num  173 179 167 195 173 184 162 169 164 168 ...
##  $ weight  : num  57 58 62 84 64 74 57 55 56 60 ...
##  $ age     : num  18 19 18 18 18 22 20 18 19 23 ...
##  $ gender  : Factor w/ 2 levels &quot;female&quot;,&quot;male&quot;: 1 1 1 2 1 2 1 1 1 2 ...
##  $ smokes  : Factor w/ 2 levels &quot;no&quot;,&quot;yes&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ alcohol : Factor w/ 2 levels &quot;no&quot;,&quot;yes&quot;: 2 2 2 2 2 2 2 2 2 2 ...
##  $ exercise: Factor w/ 3 levels &quot;low&quot;,&quot;moderate&quot;,..: 2 2 3 3 1 1 2 2 3 2 ...
##  $ ran     : Factor w/ 2 levels &quot;sat&quot;,&quot;ran&quot;: 1 2 2 1 1 2 1 1 1 2 ...
##  $ pulse1  : num  86 82 96 71 90 78 68 71 68 88 ...
##  $ pulse2  : num  88 150 176 73 88 141 72 77 68 150 ...
##  $ year    : Factor w/ 5 levels &quot;1993&quot;,&quot;1995&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  - attr(*, &quot;variable.labels&quot;)= Named chr(0) 
##   ..- attr(*, &quot;names&quot;)= chr(0) 
##  - attr(*, &quot;codepage&quot;)= int 65001</code></pre>
</div>
</div>
<div id="properties" class="section level3" number="2.3.3">
<h3><span class="header-section-number">2.3.3</span> Properties</h3>
<p>Let’s discuss the data frame <code>pulse</code>:</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="data-types-part-1.html#cb287-1" aria-hidden="true" tabindex="-1"></a>pulse <span class="ot">&lt;-</span> <span class="fu">read.table</span>( <span class="st">&quot;data/pulse.txt&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>, <span class="at">sep =</span> <span class="st">&quot;</span><span class="sc">\t</span><span class="st">&quot;</span> )</span></code></pre></div>
<pre><code># To get &#39;pulse.txt&#39; directly from the server, use:
# pulse &lt;- read.table( url( &quot;https://barmsijs.lumc.nl/R_course/index.html/tree/master/data/pulse.txt&quot; ), header = TRUE, sep = &quot;\t&quot; )</code></pre>
<p>To shorten output we will use the first 20 rows of the <code>pulse</code> data frame:</p>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="data-types-part-1.html#cb289-1" aria-hidden="true" tabindex="-1"></a>pulse <span class="ot">&lt;-</span> <span class="fu">head</span>( pulse, <span class="dv">20</span> )</span></code></pre></div>
<div id="dimensions-1" class="section level4" number="2.3.3.1">
<h4><span class="header-section-number">2.3.3.1</span> Dimensions</h4>
<p>There are several functions to get dimensions of a data frame:</p>
<ul>
<li><code>ncol( pulse )</code> provides the number of columns:</li>
</ul>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb290-1"><a href="data-types-part-1.html#cb290-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>( pulse )</span></code></pre></div>
<pre><code>## [1] 12</code></pre>
<ul>
<li><code>nrow( pulse )</code> provides the number of rows:</li>
</ul>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="data-types-part-1.html#cb292-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>( pulse )</span></code></pre></div>
<pre><code>## [1] 20</code></pre>
<ul>
<li><code>dim( pulse )</code> returns a vector with two elements: number of rows and number of columns</li>
</ul>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb294-1"><a href="data-types-part-1.html#cb294-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>( pulse )</span></code></pre></div>
<pre><code>## [1] 20 12</code></pre>
</div>
<div id="columnsrows-names" class="section level4" number="2.3.3.2">
<h4><span class="header-section-number">2.3.3.2</span> Columns/rows names</h4>
<p><code>colnames( pulse )</code> is used to get the names of the columns. In data frames, the same result is returned by <code>names( d )</code>:</p>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="data-types-part-1.html#cb296-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>( pulse )</span></code></pre></div>
<pre><code>##  [1] &quot;name&quot;     &quot;height&quot;   &quot;weight&quot;   &quot;age&quot;      &quot;gender&quot;   &quot;smokes&quot;  
##  [7] &quot;alcohol&quot;  &quot;exercise&quot; &quot;ran&quot;      &quot;pulse1&quot;   &quot;pulse2&quot;   &quot;year&quot;</code></pre>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="data-types-part-1.html#cb298-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>( pulse )</span></code></pre></div>
<pre><code>##  [1] &quot;name&quot;     &quot;height&quot;   &quot;weight&quot;   &quot;age&quot;      &quot;gender&quot;   &quot;smokes&quot;  
##  [7] &quot;alcohol&quot;  &quot;exercise&quot; &quot;ran&quot;      &quot;pulse1&quot;   &quot;pulse2&quot;   &quot;year&quot;</code></pre>
<p>To get names of the rows use:</p>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb300-1"><a href="data-types-part-1.html#cb300-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>( pulse )</span></code></pre></div>
<pre><code>##  [1] &quot;1993_A&quot; &quot;1993_B&quot; &quot;1993_C&quot; &quot;1993_D&quot; &quot;1993_E&quot; &quot;1993_F&quot; &quot;1993_G&quot; &quot;1993_H&quot;
##  [9] &quot;1993_I&quot; &quot;1993_J&quot; &quot;1993_K&quot; &quot;1993_L&quot; &quot;1993_M&quot; &quot;1993_N&quot; &quot;1993_O&quot; &quot;1993_P&quot;
## [17] &quot;1993_Q&quot; &quot;1993_R&quot; &quot;1993_S&quot; &quot;1993_T&quot;</code></pre>
</div>
</div>
<div id="content" class="section level3" number="2.3.4">
<h3><span class="header-section-number">2.3.4</span> Content</h3>
<p>A column of a data frame might be accessed through the <code>$</code> operator.</p>
<p>Additionally, the content of a data frame can be accessed with the square bracket <code>[ ]</code> (square brackets) operator used in two different ways:</p>
<ul>
<li>with one argument <code>[ col(s) ]</code> referring to a column</li>
<li>with two arguments <code>[ row(s), col(s) ]</code></li>
</ul>
<!-- Note, that sometimes it is not obvious what is returned by those operators.
When a single column is requested, should it be:

- a vector with the column elements (so, a 1-dimensional structure)?
- a data frame with a single column (so, a 2-dimensional structure)? -->
<div id="dollar-operator" class="section level4" number="2.3.4.1">
<h4><span class="header-section-number">2.3.4.1</span> Dollar operator</h4>
<p>The <code>$</code> method returns a <em>single</em> column as a <em>vector</em>:</p>
<div class="sourceCode" id="cb302"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb302-1"><a href="data-types-part-1.html#cb302-1" aria-hidden="true" tabindex="-1"></a>pulse<span class="sc">$</span>weight</span></code></pre></div>
<pre><code>##  [1]  57  58  62  84  64  74  57  55  56  60  75  58  68  59  72 110  56  70  56
## [20]  50</code></pre>
<p>When the column name is valid the returned value is a <em>vector</em>:</p>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb304-1"><a href="data-types-part-1.html#cb304-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( pulse<span class="sc">$</span>weight )</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<p>When the name is invalid, <code>NULL</code> is returned:</p>
<div class="sourceCode" id="cb306"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb306-1"><a href="data-types-part-1.html#cb306-1" aria-hidden="true" tabindex="-1"></a>pulse<span class="sc">$</span>wrong</span></code></pre></div>
<pre><code>## NULL</code></pre>
<p>Be careful, the <code>$</code> notation searches for a column name starting with a provided prefix:</p>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb308-1"><a href="data-types-part-1.html#cb308-1" aria-hidden="true" tabindex="-1"></a>pulse<span class="sc">$</span>we</span></code></pre></div>
<pre><code>##  [1]  57  58  62  84  64  74  57  55  56  60  75  58  68  59  72 110  56  70  56
## [20]  50</code></pre>
</div>
<div id="square-brackets-operator-single-argument" class="section level4" number="2.3.4.2">
<h4><span class="header-section-number">2.3.4.2</span> Square brackets operator, single argument</h4>
<p>Square brackets notation with a single argument return requested columns as a <em>data frame</em> (compare to the dollar operator section):</p>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="data-types-part-1.html#cb310-1" aria-hidden="true" tabindex="-1"></a>pulse[ <span class="st">&#39;weight&#39;</span> ]</span></code></pre></div>
<pre><code>##        weight
## 1993_A     57
## 1993_B     58
## 1993_C     62
## 1993_D     84
## 1993_E     64
## 1993_F     74
## 1993_G     57
## 1993_H     55
## 1993_I     56
## 1993_J     60
## 1993_K     75
## 1993_L     58
## 1993_M     68
## 1993_N     59
## 1993_O     72
## 1993_P    110
## 1993_Q     56
## 1993_R     70
## 1993_S     56
## 1993_T     50</code></pre>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="data-types-part-1.html#cb312-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( pulse[ <span class="st">&#39;weight&#39;</span> ] )</span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb314-1"><a href="data-types-part-1.html#cb314-1" aria-hidden="true" tabindex="-1"></a>pulse[ <span class="dv">3</span> ]</span></code></pre></div>
<pre><code>##        weight
## 1993_A     57
## 1993_B     58
## 1993_C     62
## 1993_D     84
## 1993_E     64
## 1993_F     74
## 1993_G     57
## 1993_H     55
## 1993_I     56
## 1993_J     60
## 1993_K     75
## 1993_L     58
## 1993_M     68
## 1993_N     59
## 1993_O     72
## 1993_P    110
## 1993_Q     56
## 1993_R     70
## 1993_S     56
## 1993_T     50</code></pre>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb316-1"><a href="data-types-part-1.html#cb316-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( pulse[ <span class="dv">3</span> ] )</span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<p>Since the returned object is a <code>data.frame</code>, multiple columns might be returned (for example in a different order):</p>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb318-1"><a href="data-types-part-1.html#cb318-1" aria-hidden="true" tabindex="-1"></a>pulse[ <span class="fu">c</span>( <span class="st">&#39;height&#39;</span>, <span class="st">&#39;weight&#39;</span> ) ]</span></code></pre></div>
<pre><code>##        height weight
## 1993_A    173     57
## 1993_B    179     58
## 1993_C    167     62
## 1993_D    195     84
## 1993_E    173     64
## 1993_F    184     74
## 1993_G    162     57
## 1993_H    169     55
## 1993_I    164     56
## 1993_J    168     60
## 1993_K    170     75
## 1993_L    178     58
## 1993_M    170     68
## 1993_N    187     59
## 1993_O    180     72
## 1993_P    185    110
## 1993_Q    170     56
## 1993_R    180     70
## 1993_S    166     56
## 1993_T    155     50</code></pre>
<p>When a name is invalid, an error is produced:</p>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb320-1"><a href="data-types-part-1.html#cb320-1" aria-hidden="true" tabindex="-1"></a>pulse[ <span class="st">&#39;wrong&#39;</span> ]</span></code></pre></div>
<pre><code>## Error in `[.data.frame`(pulse, &quot;wrong&quot;): undefined columns selected</code></pre>
</div>
<div id="square-brackets-operator-two-arguments" class="section level4" number="2.3.4.3">
<h4><span class="header-section-number">2.3.4.3</span> Square brackets operator, two arguments</h4>
<p>Single brackets notation with two arguments <code>[ row(s), col(s) ]</code> might be used to get (multiple) row(s) and (multiple) column(s):</p>
<div class="sourceCode" id="cb322"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb322-1"><a href="data-types-part-1.html#cb322-1" aria-hidden="true" tabindex="-1"></a>pulse[ <span class="fu">c</span>( <span class="dv">1</span>, <span class="dv">3</span> ), <span class="fu">c</span>( <span class="st">&#39;height&#39;</span>, <span class="st">&#39;weight&#39;</span> ) ]</span></code></pre></div>
<pre><code>##        height weight
## 1993_A    173     57
## 1993_C    167     62</code></pre>
<div class="sourceCode" id="cb324"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb324-1"><a href="data-types-part-1.html#cb324-1" aria-hidden="true" tabindex="-1"></a>pulse[ <span class="fu">c</span>( <span class="st">&quot;1993_C&quot;</span>, <span class="st">&quot;1993_A&quot;</span>, <span class="st">&quot;wrong&quot;</span> ), <span class="fu">c</span>( <span class="st">&#39;height&#39;</span>, <span class="st">&#39;weight&#39;</span> ) ]</span></code></pre></div>
<pre><code>##        height weight
## 1993_C    167     62
## 1993_A    173     57
## NA         NA     NA</code></pre>
<p>Warning: notice the difference of the class of the output when only a single column is requested:</p>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb326-1"><a href="data-types-part-1.html#cb326-1" aria-hidden="true" tabindex="-1"></a>pulse[ , <span class="fu">c</span>( <span class="st">&#39;height&#39;</span>, <span class="st">&#39;weight&#39;</span> ) ]</span></code></pre></div>
<pre><code>##        height weight
## 1993_A    173     57
## 1993_B    179     58
## 1993_C    167     62
## 1993_D    195     84
## 1993_E    173     64
## 1993_F    184     74
## 1993_G    162     57
## 1993_H    169     55
## 1993_I    164     56
## 1993_J    168     60
## 1993_K    170     75
## 1993_L    178     58
## 1993_M    170     68
## 1993_N    187     59
## 1993_O    180     72
## 1993_P    185    110
## 1993_Q    170     56
## 1993_R    180     70
## 1993_S    166     56
## 1993_T    155     50</code></pre>
<div class="sourceCode" id="cb328"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb328-1"><a href="data-types-part-1.html#cb328-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( pulse[ , <span class="fu">c</span>( <span class="st">&#39;height&#39;</span>, <span class="st">&#39;weight&#39;</span> ) ] )</span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<div class="sourceCode" id="cb330"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb330-1"><a href="data-types-part-1.html#cb330-1" aria-hidden="true" tabindex="-1"></a>pulse[ , <span class="fu">c</span>( <span class="st">&#39;weight&#39;</span> ) ]</span></code></pre></div>
<pre><code>##  [1]  57  58  62  84  64  74  57  55  56  60  75  58  68  59  72 110  56  70  56
## [20]  50</code></pre>
<div class="sourceCode" id="cb332"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb332-1"><a href="data-types-part-1.html#cb332-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( pulse[ , <span class="fu">c</span>( <span class="st">&#39;weight&#39;</span> ) ] )</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<p>Empty index field means “all” rows or columns:</p>
<div class="sourceCode" id="cb334"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb334-1"><a href="data-types-part-1.html#cb334-1" aria-hidden="true" tabindex="-1"></a>pulse[ , ]</span></code></pre></div>
<pre><code>##             name height weight age gender smokes alcohol exercise ran pulse1
## 1993_A    Bonnie    173     57  18 female     no     yes moderate sat     86
## 1993_B   Melanie    179     58  19 female     no     yes moderate ran     82
## 1993_C  Consuelo    167     62  18 female     no     yes     high ran     96
## 1993_D    Travis    195     84  18   male     no     yes     high sat     71
## 1993_E     Lauri    173     64  18 female     no     yes      low sat     90
## 1993_F    George    184     74  22   male     no     yes      low ran     78
## 1993_G    Cherry    162     57  20 female     no     yes moderate sat     68
## 1993_H Francesca    169     55  18 female     no     yes moderate sat     71
## 1993_I     Sonja    164     56  19 female     no     yes     high sat     68
## 1993_J      Troy    168     60  23   male     no     yes moderate ran     88
## 1993_K    Roland    170     75  20   male     no     yes     high ran     76
## 1993_L Frederick    178     58  19   male     no      no      low sat     74
## 1993_M    Justin    170     68  22   male    yes     yes moderate sat     70
## 1993_N    Ernest    187     59  18   male     no     yes     high sat     78
## 1993_O  Salvador    180     72  18   male     no     yes moderate sat     69
## 1993_P    Mathew    185    110  22   male     no     yes      low sat     77
## 1993_Q    Leslie    170     56  19   male     no      no      low sat     64
## 1993_R   Raymond    180     70  18   male     no     yes moderate ran     80
## 1993_S    Nicole    166     56  21 female    yes      no moderate sat     83
## 1993_T     Maura    155     50  19 female     no      no moderate sat     78
##        pulse2 year
## 1993_A     88 1993
## 1993_B    150 1993
## 1993_C    176 1993
## 1993_D     73 1993
## 1993_E     88 1993
## 1993_F    141 1993
## 1993_G     72 1993
## 1993_H     77 1993
## 1993_I     68 1993
## 1993_J    150 1993
## 1993_K     88 1993
## 1993_L     76 1993
## 1993_M     71 1993
## 1993_N     82 1993
## 1993_O     67 1993
## 1993_P     73 1993
## 1993_Q     63 1993
## 1993_R    146 1993
## 1993_S     79 1993
## 1993_T     79 1993</code></pre>
<div class="sourceCode" id="cb336"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb336-1"><a href="data-types-part-1.html#cb336-1" aria-hidden="true" tabindex="-1"></a>pulse[ , <span class="fu">c</span>( <span class="st">&#39;height&#39;</span>, <span class="st">&#39;weight&#39;</span> ) ]</span></code></pre></div>
<pre><code>##        height weight
## 1993_A    173     57
## 1993_B    179     58
## 1993_C    167     62
## 1993_D    195     84
## 1993_E    173     64
## 1993_F    184     74
## 1993_G    162     57
## 1993_H    169     55
## 1993_I    164     56
## 1993_J    168     60
## 1993_K    170     75
## 1993_L    178     58
## 1993_M    170     68
## 1993_N    187     59
## 1993_O    180     72
## 1993_P    185    110
## 1993_Q    170     56
## 1993_R    180     70
## 1993_S    166     56
## 1993_T    155     50</code></pre>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb338-1"><a href="data-types-part-1.html#cb338-1" aria-hidden="true" tabindex="-1"></a>pulse[ <span class="fu">c</span>( <span class="st">&quot;1993_C&quot;</span>, <span class="st">&quot;1993_A&quot;</span> ), ]</span></code></pre></div>
<pre><code>##            name height weight age gender smokes alcohol exercise ran pulse1
## 1993_C Consuelo    167     62  18 female     no     yes     high ran     96
## 1993_A   Bonnie    173     57  18 female     no     yes moderate sat     86
##        pulse2 year
## 1993_C    176 1993
## 1993_A     88 1993</code></pre>
<hr />
<blockquote>
<p><em>Quick task(s)</em>:</p>
<p>Solve <a href="03_data_frames.tasks.nocode.html#dataframes">the task(s)</a>, and check your solution(s) <a href="03_data_frames.tasks.code.html#dataframes">here</a>.</p>
</blockquote>
<hr />
</div>
</div>
</div>
<div id="matrices" class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> Matrices</h2>
<div id="what-is-a-matrix" class="section level3" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> What is a matrix</h3>
<center>
<img src="figure/Data_types_mdfl.png" title="fig:" alt="Vectors" />
</center>
<p>Matrix is a two-dimensional array of elements of the same type.</p>
<p>Rows and columns are addressed by numerical indices.</p>
<p>Rows and columns might also get names. The names might be used for indexing.</p>
</div>
<div id="creation" class="section level3" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> Creation</h3>
<p>A matrix can be constructed from a vector. Depending on the arguments, elements are put to the matrix in a different order:</p>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="data-types-part-1.html#cb340-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">nrow =</span> <span class="dv">2</span> );</span>
<span id="cb340-2"><a href="data-types-part-1.html#cb340-2" aria-hidden="true" tabindex="-1"></a>m</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    3    5
## [2,]    2    4    6</code></pre>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb342-1"><a href="data-types-part-1.html#cb342-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span> );</span>
<span id="cb342-2"><a href="data-types-part-1.html#cb342-2" aria-hidden="true" tabindex="-1"></a>m</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    2    3
## [2,]    4    5    6</code></pre>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb344-1"><a href="data-types-part-1.html#cb344-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">ncol =</span> <span class="dv">2</span> );</span>
<span id="cb344-2"><a href="data-types-part-1.html#cb344-2" aria-hidden="true" tabindex="-1"></a>m</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    4
## [2,]    2    5
## [3,]    3    6</code></pre>
<p>The class of <code>m</code> is:</p>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb346-1"><a href="data-types-part-1.html#cb346-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( m )</span></code></pre></div>
<pre><code>## [1] &quot;matrix&quot; &quot;array&quot;</code></pre>
<p>Function <code>str</code> gives a compact display of an object structure/content:</p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="data-types-part-1.html#cb348-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>( m )</span></code></pre></div>
<pre><code>##  int [1:3, 1:2] 1 2 3 4 5 6</code></pre>
</div>
<div id="dimensions-2" class="section level3" number="2.4.3">
<h3><span class="header-section-number">2.4.3</span> Dimensions</h3>
<p>There are several functions to get dimensions of a matrix:</p>
<ul>
<li><code>ncol( m )</code> provides the number of columns:</li>
</ul>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb350-1"><a href="data-types-part-1.html#cb350-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>( m )</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<ul>
<li><code>nrow( m )</code> provides the number of rows:</li>
</ul>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb352-1"><a href="data-types-part-1.html#cb352-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>( m )</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<ul>
<li><code>dim( m )</code> returns a vector with two elements: number of rows and number of columns</li>
</ul>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb354-1"><a href="data-types-part-1.html#cb354-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>( m )</span></code></pre></div>
<pre><code>## [1] 3 2</code></pre>
</div>
<div id="settinggetting-names-of-the-columns-and-rows" class="section level3" number="2.4.4">
<h3><span class="header-section-number">2.4.4</span> Setting/getting names of the columns and rows</h3>
<p><code>colnames( m )</code> and <code>rownames( m )</code> are used to set and get the names of matrix columns and rows:</p>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb356-1"><a href="data-types-part-1.html#cb356-1" aria-hidden="true" tabindex="-1"></a>m</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    4
## [2,]    2    5
## [3,]    3    6</code></pre>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb358-1"><a href="data-types-part-1.html#cb358-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>( m ) <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span> )</span>
<span id="cb358-2"><a href="data-types-part-1.html#cb358-2" aria-hidden="true" tabindex="-1"></a>m</span></code></pre></div>
<pre><code>##      A B
## [1,] 1 4
## [2,] 2 5
## [3,] 3 6</code></pre>
<div class="sourceCode" id="cb360"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb360-1"><a href="data-types-part-1.html#cb360-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>( m ) <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="st">&quot;X&quot;</span>, <span class="st">&quot;Y&quot;</span>, <span class="st">&quot;Z&quot;</span> )</span>
<span id="cb360-2"><a href="data-types-part-1.html#cb360-2" aria-hidden="true" tabindex="-1"></a>m</span></code></pre></div>
<pre><code>##   A B
## X 1 4
## Y 2 5
## Z 3 6</code></pre>
<p>To get names use:</p>
<div class="sourceCode" id="cb362"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb362-1"><a href="data-types-part-1.html#cb362-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>( m )</span></code></pre></div>
<pre><code>## [1] &quot;X&quot; &quot;Y&quot; &quot;Z&quot;</code></pre>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb364-1"><a href="data-types-part-1.html#cb364-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>( m )</span></code></pre></div>
<pre><code>## [1] &quot;A&quot; &quot;B&quot;</code></pre>
</div>
<div id="getting-matrix-elements" class="section level3" number="2.4.5">
<h3><span class="header-section-number">2.4.5</span> Getting matrix elements</h3>
<p>Single brackets notation with two arguments <code>[ row(s), col(s) ]</code> might be used to get specified row(s) and column(s). By default single rows/cols will get reduced to a vector.</p>
<div class="sourceCode" id="cb366"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb366-1"><a href="data-types-part-1.html#cb366-1" aria-hidden="true" tabindex="-1"></a>m[ <span class="dv">3</span>, <span class="dv">1</span> ]</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb368"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb368-1"><a href="data-types-part-1.html#cb368-1" aria-hidden="true" tabindex="-1"></a>m[ <span class="fu">c</span>( <span class="dv">2</span>, <span class="dv">3</span> ), <span class="dv">1</span> ]</span></code></pre></div>
<pre><code>## Y Z 
## 2 3</code></pre>
<div class="sourceCode" id="cb370"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb370-1"><a href="data-types-part-1.html#cb370-1" aria-hidden="true" tabindex="-1"></a>m[ <span class="fu">c</span>( <span class="dv">2</span>, <span class="dv">3</span> ), <span class="fu">c</span>( <span class="st">&quot;B&quot;</span>, <span class="st">&quot;A&quot;</span> ) ]</span></code></pre></div>
<pre><code>##   B A
## Y 5 2
## Z 6 3</code></pre>
<div class="sourceCode" id="cb372"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb372-1"><a href="data-types-part-1.html#cb372-1" aria-hidden="true" tabindex="-1"></a>m[ <span class="fu">c</span>( F, T, T ), <span class="fu">c</span>( <span class="st">&quot;B&quot;</span>, <span class="st">&quot;A&quot;</span> ) ]</span></code></pre></div>
<pre><code>##   B A
## Y 5 2
## Z 6 3</code></pre>
<p>Notice the difference in the output class when only a single element is requested:</p>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb374-1"><a href="data-types-part-1.html#cb374-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( m[ <span class="dv">3</span>, <span class="dv">1</span> ] )</span></code></pre></div>
<pre><code>## [1] &quot;integer&quot;</code></pre>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb376-1"><a href="data-types-part-1.html#cb376-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( m[ <span class="fu">c</span>( <span class="dv">2</span>, <span class="dv">3</span> ), <span class="fu">c</span>( <span class="st">&quot;B&quot;</span>, <span class="st">&quot;A&quot;</span> ) ] )</span></code></pre></div>
<pre><code>## [1] &quot;matrix&quot; &quot;array&quot;</code></pre>
<p>Dropping of <code>matrix</code> dimensionality might be prevented:</p>
<div class="sourceCode" id="cb378"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb378-1"><a href="data-types-part-1.html#cb378-1" aria-hidden="true" tabindex="-1"></a>m[ <span class="dv">3</span>, <span class="dv">1</span> ]</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb380"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb380-1"><a href="data-types-part-1.html#cb380-1" aria-hidden="true" tabindex="-1"></a>m[ <span class="dv">3</span>, <span class="dv">1</span>, drop <span class="ot">=</span> <span class="cn">FALSE</span> ]</span></code></pre></div>
<pre><code>##   A
## Z 3</code></pre>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb382-1"><a href="data-types-part-1.html#cb382-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>( m[ <span class="dv">3</span>, <span class="dv">1</span>, <span class="at">drop =</span> <span class="cn">FALSE</span> ] )</span></code></pre></div>
<pre><code>## [1] &quot;matrix&quot; &quot;array&quot;</code></pre>
<p>Empty index field means “all” rows or columns:</p>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb384-1"><a href="data-types-part-1.html#cb384-1" aria-hidden="true" tabindex="-1"></a>m[ , <span class="fu">c</span>( <span class="st">&quot;B&quot;</span>, <span class="st">&quot;A&quot;</span> ) ]</span></code></pre></div>
<pre><code>##   B A
## X 4 1
## Y 5 2
## Z 6 3</code></pre>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb386-1"><a href="data-types-part-1.html#cb386-1" aria-hidden="true" tabindex="-1"></a>m[ <span class="fu">c</span>( <span class="st">&quot;Z&quot;</span>, <span class="st">&quot;X&quot;</span>, <span class="st">&quot;Y&quot;</span> ), ]</span></code></pre></div>
<pre><code>##   A B
## Z 3 6
## X 1 4
## Y 2 5</code></pre>
<div class="sourceCode" id="cb388"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb388-1"><a href="data-types-part-1.html#cb388-1" aria-hidden="true" tabindex="-1"></a>m[ , ]</span></code></pre></div>
<pre><code>##   A B
## X 1 4
## Y 2 5
## Z 3 6</code></pre>
</div>
<div id="useful-matrix-functions" class="section level3" number="2.4.6">
<h3><span class="header-section-number">2.4.6</span> Useful matrix functions</h3>
<p>Short summary of matrix operations: <a href="http://www.statmethods.net/advstats/matrix.html" class="uri">http://www.statmethods.net/advstats/matrix.html</a></p>
<div id="rowcolumns-meanssums" class="section level4" number="2.4.6.1">
<h4><span class="header-section-number">2.4.6.1</span> Row/columns means/sums</h4>
<div class="sourceCode" id="cb390"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb390-1"><a href="data-types-part-1.html#cb390-1" aria-hidden="true" tabindex="-1"></a>m</span></code></pre></div>
<pre><code>##   A B
## X 1 4
## Y 2 5
## Z 3 6</code></pre>
<div class="sourceCode" id="cb392"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb392-1"><a href="data-types-part-1.html#cb392-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rowMeans</span>( m )</span></code></pre></div>
<pre><code>##   X   Y   Z 
## 2.5 3.5 4.5</code></pre>
<div class="sourceCode" id="cb394"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb394-1"><a href="data-types-part-1.html#cb394-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rowSums</span>( m )</span></code></pre></div>
<pre><code>## X Y Z 
## 5 7 9</code></pre>
<div class="sourceCode" id="cb396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb396-1"><a href="data-types-part-1.html#cb396-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colMeans</span>( m )</span></code></pre></div>
<pre><code>## A B 
## 2 5</code></pre>
<div class="sourceCode" id="cb398"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb398-1"><a href="data-types-part-1.html#cb398-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>( m )</span></code></pre></div>
<pre><code>##  A  B 
##  6 15</code></pre>
</div>
<div id="transposition" class="section level4" number="2.4.6.2">
<h4><span class="header-section-number">2.4.6.2</span> (*) Transposition</h4>
<div class="sourceCode" id="cb400"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb400-1"><a href="data-types-part-1.html#cb400-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">matrix</span>( <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">nrow =</span> <span class="dv">3</span> );</span>
<span id="cb400-2"><a href="data-types-part-1.html#cb400-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>( m ) <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span> )</span>
<span id="cb400-3"><a href="data-types-part-1.html#cb400-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>( m ) <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="st">&quot;X&quot;</span>, <span class="st">&quot;Y&quot;</span>, <span class="st">&quot;Z&quot;</span> )</span>
<span id="cb400-4"><a href="data-types-part-1.html#cb400-4" aria-hidden="true" tabindex="-1"></a>m</span></code></pre></div>
<pre><code>##   A B
## X 1 4
## Y 2 5
## Z 3 6</code></pre>
<div class="sourceCode" id="cb402"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb402-1"><a href="data-types-part-1.html#cb402-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t</span>(m)</span></code></pre></div>
<pre><code>##   X Y Z
## A 1 2 3
## B 4 5 6</code></pre>
</div>
<div id="matrix-multiplication" class="section level4" number="2.4.6.3">
<h4><span class="header-section-number">2.4.6.3</span> (*) Matrix multiplication</h4>
<div class="sourceCode" id="cb404"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb404-1"><a href="data-types-part-1.html#cb404-1" aria-hidden="true" tabindex="-1"></a>m</span></code></pre></div>
<pre><code>##   A B
## X 1 4
## Y 2 5
## Z 3 6</code></pre>
<div class="sourceCode" id="cb406"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb406-1"><a href="data-types-part-1.html#cb406-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t</span>( m )</span></code></pre></div>
<pre><code>##   X Y Z
## A 1 2 3
## B 4 5 6</code></pre>
<div class="sourceCode" id="cb408"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb408-1"><a href="data-types-part-1.html#cb408-1" aria-hidden="true" tabindex="-1"></a>m <span class="sc">%*%</span> <span class="fu">t</span>( m )</span></code></pre></div>
<pre><code>##    X  Y  Z
## X 17 22 27
## Y 22 29 36
## Z 27 36 45</code></pre>
</div>
<div id="element-wise-multiplication" class="section level4" number="2.4.6.4">
<h4><span class="header-section-number">2.4.6.4</span> (*) Element-wise multiplication</h4>
<div class="sourceCode" id="cb410"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb410-1"><a href="data-types-part-1.html#cb410-1" aria-hidden="true" tabindex="-1"></a>m</span></code></pre></div>
<pre><code>##   A B
## X 1 4
## Y 2 5
## Z 3 6</code></pre>
<div class="sourceCode" id="cb412"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb412-1"><a href="data-types-part-1.html#cb412-1" aria-hidden="true" tabindex="-1"></a>m<span class="sc">+</span><span class="dv">1</span></span></code></pre></div>
<pre><code>##   A B
## X 2 5
## Y 3 6
## Z 4 7</code></pre>
<div class="sourceCode" id="cb414"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb414-1"><a href="data-types-part-1.html#cb414-1" aria-hidden="true" tabindex="-1"></a>m <span class="sc">*</span> (m<span class="sc">+</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>##    A  B
## X  2 20
## Y  6 30
## Z 12 42</code></pre>
<hr />
<blockquote>
<p><em>Quick task(s)</em>:</p>
<p>Solve <a href="05_matrices.tasks.nocode.html#corMatrix">the task(s)</a>, and check your solution(s) <a href="05_matrices.tasks.code.html#corMatrix">here</a>.</p>
</blockquote>
<hr />

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="basics-of-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="data-types-part-2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown-demo.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
